# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-04 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=68)),
                ('num', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '图片展示表',
                'verbose_name_plural': '图片展示表',
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_path', models.FileField(max_length=128, upload_to='')),
            ],
            options={
                'verbose_name': '文件路径表',
                'verbose_name_plural': '文件路径表',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(max_length=50)),
                ('log_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': '用户标注关系表',
                'verbose_name_plural': '用户标注关系表',
            },
        ),
        migrations.CreateModel(
            name='ResultTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_dir', models.CharField(max_length=20)),
                ('save_path', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, '未标注'), (1, '已标注')])),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facecluster.Person')),
            ],
            options={
                'verbose_name': '标注结果表',
                'verbose_name_plural': '标注结果表',
            },
        ),
        migrations.CreateModel(
            name='TraTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tra_result', models.CharField(max_length=64)),
                ('tra_time', models.DateTimeField()),
                ('type', models.CharField(max_length=128)),
                ('path_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facecluster.Path')),
            ],
            options={
                'verbose_name': '遍历结果表',
                'verbose_name_plural': '遍历结果表',
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, '标注员'), (2, '审核员'), (3, '管理员')], verbose_name='角色选择')),
                ('name', models.CharField(max_length=20, verbose_name='用户姓名')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用户列表',
                'verbose_name_plural': '用户列表',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facecluster.UserList'),
        ),
        migrations.AddField(
            model_name='imgmodel',
            name='per_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facecluster.Person'),
        ),
    ]
